services:
  telegram_reviews_bot:
    build:
      context: .
      dockerfile: ./telegram_reviews_bot/Dockerfile
    container_name: telegram_reviews_bot
    env_file:
      - ./telegram_reviews_bot/.env
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
